#
# ps8pr3.py  (Problem Set 8, Problem 3)
#
# Markov text generation      
#
import random

def create_dictionary(filename):
    """  takes a string representing the name of a text file, and
        that returns a dictionary of key-value pairs
    """
    file = open(filename, 'r')
    text = file.read()
    file.close()
    words = text.split()
    d = {}
    current_word = '$'
    
    for next_word in words:
        if current_word not in d:
            d[current_word] = [next_word]
        else:
            d[current_word] += [next_word]
        if next_word[-1] == '.' or next_word[-1] == '!' or next_word[-1] == '?':
            current_word = '$'
        else:
            current_word = next_word
    return d

def generate_text(word_dict, num_words):
    """ takes as parameters a dictionary of word transitions
        (generated by the create_dictionary function) named
        word_dict and a positive integer named num_words
    """
    current_word = '$'
    for i in range(num_words):
        word_list = word_dict[current_word]
        next_word = random.choice(word_list)
        print(next_word, end=' ')
        if next_word[-1] == '.' or next_word[-1] == '!' or next_word[-1] == '?':
            current_word = '$'
        elif next_word not in word_dict:
            current_word = '$'
        else:
            current_word = next_word
    print()        
